djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from unique_eshop.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('admin/', admin.site.urls),
                  path('recentAccessories/', recentAccessories, name='recentAccessories'),
                  path('register/', register, name='register'),
                  path('sale/', sale, name='sale'),
                  path('details/', details, name='details'),
                  path('deleteSale/', deleteSale, name='deleteSale'),
                  path('quantityDecrease/', quantityDecrease, name='quantityDecrease'),
                  path('quantity/', quantity, name='quantity'),
                  path('addAccessory/', addAccessory, name='addAccessory'),
                  path('search_products', search_products, name='search_products'),
                  path('process_payment/', process_payment, name='process_payment'),
                  path('home', home, name='home'),
                  path('', home, name='home')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unique_eshop/models.py
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User, Group
from django.db import models
from django.contrib.auth.models import AbstractUser

CATEGORIES = [
    ("gjerdani", "ѓердани"),
    ("obetki", "обетки"),
    ("broshovi", "брошови"),
    ("prsteni", "прстени"),
    ("kosa", "додатоци за во коса"),
    ("alki", "алки"),

]


class Accessory(models.Model):
    name = models.CharField(max_length=40)
    description = models.TextField()
    color = models.CharField(max_length=40)
    quantity = models.IntegerField()
    price = models.IntegerField()
    category = models.CharField(max_length=8, choices=CATEGORIES)
    mainImage = models.URLField(null=True, blank=True)
    secondImage = models.URLField(null=True, blank=True)
    datetime = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class ShoppingCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Shopping Cart of user {self.user.username}"

class Sale(models.Model):
    accessory = models.ForeignKey(Accessory, on_delete=models.CASCADE, null=True, blank=True)
    shoppingCart = models.ForeignKey(ShoppingCart, on_delete=models.CASCADE, null=True, blank=True)
    totalPrice = models.IntegerField(null=True, blank=True)
    numOfPieces = models.IntegerField(null=True, blank=True)


class Payment(models.Model):
    accessory = models.ForeignKey(Accessory, on_delete=models.CASCADE, null=True, blank=True)
    shoppingCart = models.ForeignKey(ShoppingCart, on_delete=models.CASCADE, null=True, blank=True)
    numOfPieces = models.IntegerField(null=True, blank=True)
    successfully_paid = models.BooleanField(default=False, null=True)

    def __str__(self):
        return f"User: {self.shoppingCart.user.username} bought {self.accessory.name} with quantity of: {self.numOfPieces}."

@receiver(post_save, sender=User)
def create_shopping_cart(sender, instance, created, **kwargs):
    if created:
        shopping_cart = ShoppingCart.objects.create(user=instance)
        Sale.objects.create(shoppingCart=shopping_cart, accessory=None, totalPrice=0, numOfPieces=0)


post_save.connect(create_shopping_cart, sender=User)

templates/addAccessory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add New Accessory</title>
    <style>
        .form-group {
            display: flex;
            flex-direction: column;
            padding: 0.4rem;
        }

        .form-group input {
            margin: auto;

            width: 15rem;
            height: 2.1rem;
        {#margin-bottom: 1rem;#} background-color: #E8C8A8;
            border-radius: 2px;
            border: solid 2px #2B0320;

        }

        label {
            margin: auto;
            font-size: 1em;
            color: #2B0320;
        }

        option, select {
            background-color: #E8C8A8;
        }

        textarea {
            width: 15rem;
            height: 2.5rem;
            background-color: transparent;
            margin-left: 12rem;
            border: solid 2px #2B0320;
        }
    </style>
</head>
<body>
{% extends 'base.html' %}

{% block breadcrumps %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <div class="pl-5  container">
            <ol class="breadcrumb pl-3 text-muted">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Почетна</a></li>
                <li class="breadcrumb-item"><a href="{% url 'addAccessory' %}">Додавање на нов производ</a></li>
            </ol>
        </div>
    </nav>
{% endblock breadcrumps %}

{% block content %}
    <div class="container" style="background-color: #E5C3A6;">
        <div class="container" style="height: 30rem; padding-top: 5rem">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_name">Име на производот</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label for="id_description">Опис на производот</label>
                            <div class="w-50 ml-5" style="    margin-left: 12rem;">{{ form.description }}</div>

                        </div>
                        <div class="form-group">
                            <label for="id_color">Боја на производот</label>
                            {{ form.color }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_quantity">Количина на производот</label>
                            {{ form.quantity }}
                        </div>
                        <div class="form-group">
                            <label for="id_price">Цена на производот</label>
                            {{ form.price }}
                        </div>
                        <div class="form-group">
                            <label for="id_category">Категорија на производот</label>
                            <div class="mx-auto"
                                 style="background-color: transparent">                            {{ form.category }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_mainImage">Главна слика</label>
                            {{ form.mainImage }}
                        </div>
                    </div>
                    <div class="col-md-6 pb-5">
                        <div class="form-group">
                            <label for="id_secondImage">Споредна слика</label>
                            {{ form.secondImage }}
                        </div>
                    </div>
                </div>
                <button class="container button rounded-pill border-0 py-1 px-3 mt-2 text-light"
                        style="background-color: #784D59;width: 12rem; margin-left: 34rem;">Додади го производот
                </button>
            </form>
        </div>
    </div>
{% endblock content %}
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        .breadcrumb .breadcrumb-item a {
            color: lightgray; /* Use text-muted color */
            text-decoration: none !important; /* Remove underline */
        }

        .breadcrumb .breadcrumb-item:last-child a {
            color: #2B0320 !important; /* Apply red color */
        }

        body {
            font-family: "Vollkorn", serif;
        }
    </style>
</head>
<body class="font-family: Vollkorn">
{% block nav %}
    <div class="border border-bottom border-light fixed-top" style="background-color: #ffffff">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                <span class="navbar-brand col-8"><svg xmlns="http://www.w3.org/2000/svg" width="2.2rem" height="2.2rem"
                                                      fill="currentColor" class="bi bi-gem" viewBox="0 0 16 16">
  <path d="M3.1.7a.5.5 0 0 1 .4-.2h9a.5.5 0 0 1 .4.2l2.976 3.974c.149.185.156.45.01.644L8.4 15.3a.5.5 0 0 1-.8 0L.1 5.3a.5.5 0 0 1 0-.6l3-4zm11.386 3.785-1.806-2.41-.776 2.413 2.582-.003zm-3.633.004.961-2.989H4.186l.963 2.995 5.704-.006zM5.47 5.495 8 13.366l2.532-7.876-5.062.005zm-1.371-.999-.78-2.422-1.818 2.425 2.598-.003zM1.499 5.5l5.113 6.817-2.192-6.82L1.5 5.5zm7.889 6.817 5.123-6.83-2.928.002-2.195 6.828z"/>
</svg><i>Unique</i></span>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarNavDropdown"
                            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            {% if not user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="{% url 'recentAccessories' %}"
                                       onclick="setActiveLink(this)">Најново</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'home' %}" onclick="setActiveLink(this)">Почетна</a>
                            </li>
                            {% if user.is_authenticated and not user.is_superuser %}

                                <li class="nav-item mt-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#784D59"
                                         class="bi bi-cart-check" viewBox="0 0 16 16">
                                        <path d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
                                        <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                                    </svg>
                                </li>
                                <li class="nav-item">

                                    <form method="get" action="{% url 'sale' %}">
                                        {% csrf_token %}
                                        <input class="border-0 mt-2" type="submit"
                                               style="background-color: transparent; "
                                               value="Кошничка">

                                    </form>

                                </li>
                            {% endif %}
                            {% if user.is_superuser %}
                                <li class="nav-item">
                                    <a class="nav-link active" href="{% url 'addAccessory' %}"
                                       onclick="setActiveLink(this)">Додани нов производ
                                    </a>
                                </li>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <li class="nav-item mx-1 mt-2">{{ user.username }}</li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="{% url 'logout' %}"
                                       onclick="setActiveLink(this)">Одјава</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link active" href="{% url 'login' %}"
                                       onclick="setActiveLink(this)">Најава</a>
                                </li>
                                <li class="nav-item mt-2 text-muted">/</li>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link active" href="{% url 'register' %}"
                                       onclick="setActiveLink(this)">Регистрација</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
{% endblock nav %}
{#<div style="height: rem"></div>#}
{% block breadcrumps %}

{% endblock breadcrumps %}

{% block content %}

{% endblock content %}


</body>
</html>

templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
{% extends 'base.html' %}
{% block breadcrumps %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <div class="pl-5  container">
            <ol class="breadcrumb pl-3 text-muted">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Почетна</a></li>
                <li class="breadcrumb-item"><a href="{% url 'details'%}">Детали</a></li>

            </ol>
        </div>
    </nav>
{% endblock breadcrumps %}
{% block content %}

    <div class="container px-4 d-flex align-items-center" style="background-color: #E5C3A6; height: 35rem">
        <div class="row">
            <img class="col-4" src="{{ a.mainImage }}">
            <img class="col-4" src="{{ a.secondImage }}">
            <div class="text-center col" style="padding-top: 10rem">
                <h5 style="color:#2B0320;">Име: <span class="fst-italic fw-bold">{{ a.name }}</span></h5>
                <h6 style="color:#2B0320;">Цена: {{ a.price }}</h6>
                <h6 style="color:#2B0320;">Боја: {{ a.color }}</h6>
                <h6 style="color:#2B0320;">Категорија: {{ a.category }}</h6>

                <h6 style="color:#2B0320;">Достапна количина: {{ a.quantity }}</h6>
                {% if not user.is_superuser %}
                    <div class="button rounded-pill border-0 mt-5 py-1 px-2 text-light container"
                         style="background-color: #784D59; width: 15rem">

                        <form method="post" action="{% url 'sale' %}">
                            {% csrf_token %}

                            <input type="hidden" value="{{ a.name }}" name="name" id="name">

                            <input class="border-0" type="submit" style="background-color: transparent; color: #F6E4FF "
                                   value="Додади во кошничка" onclick="validateClick(event)">

                        </form>
                    </div>
                {% endif %}

            </div>
        </div>


    </div>
      <div class="container-fluid d-flex flex-column align-items-center justify-content-center" style="background-color: #E5C3A6; height: 5rem; margin-top: 10rem ">
        <p class="tex-center">КОНТАКТ: unique@gmail.com +389 75 301 213
        </p>
    </div>
    <script>
        var isAuthenticated = {{ user.is_authenticated|yesno:"true,false" }};

        function validateClick(event) {
            if (!isAuthenticated) {
                event.preventDefault();
                showAlert("Ве молиме регистрирајте се / најавете се за да продолжите со купување", "#855662");
            } else {
                showAlert("Производот успешно е додаден во кошничката", "#9E7276");
            }
        }


        function showAlert(message, color) {
            var alertBox = document.createElement("div");
            alertBox.style.backgroundColor = color;
            alertBox.style.color = "white";
            alertBox.style.padding = "10px";
            alertBox.style.borderRadius = "5px";
            alertBox.textContent = message;

            // Center the alert box horizontally and vertically
            alertBox.style.position = "fixed";
            alertBox.style.top = "50%";
            alertBox.style.left = "50%";
            alertBox.style.transform = "translate(-50%, -50%)";
            alertBox.style.zIndex = "9999";

            document.body.appendChild(alertBox);

            setTimeout(function () {
                alertBox.remove();
            }, 3000);
        }

    </script>
{% endblock %}

</body>
</html>

templates/home.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/js/bootstrap.bundle.min.js"></script>
    <!-- Bootstrap dependencies: Popper.js, jQuery -->
    <script src="https://unpkg.com/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://unpkg.com/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>

    {#    <link rel="stylesheet" href="{% static 'custom_slider.css' %}">#}
    {#    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>#}
    {#    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>#}
    {#    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">#}

    <style>
        .image-container {
            position: relative;
            display: inline-block;
        }

        .image-container img {
            display: block;

        }

        .image-container .hover-image {
            position: absolute;
            top: 0;
            left: 0;
            display: none;
        }

        .image-container:hover .hover-image {
            display: block;
        }
    </style>
</head>
<body>
{% extends 'base.html' %}

{% block breadcrumps %}
    {#    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">#}
    {#        <div class="pl-5  container">#}
    {#            <ol class="breadcrumb pl-3 text-muted">#}
    {#                <li class="breadcrumb-item"><a href="{% url 'home' %}">Почетна</a></li>#}
    {##}
    {#            </ol>#}
    {#        </div>#}
    {#    </nav>#}
{% endblock breadcrumps %}

{% block content %}

    <div class="container-fluid mt-0" style="background-color: #E5C3A6; height: 44rem">
        <div class="row">
            <div class="col-5 p-0 "
                 style="background-image: url('https://cdn.shopify.com/s/files/1/0357/5673/products/ana-earrings-mop-model-3-750.jpg?v=1668779528');
                         {#object-fit: cover;#}
                         background-repeat: no-repeat;">
                <div class="text-center" style="height: 44rem; padding-top: 31rem">
                    <h3 class="text-light fw-bold">НАЈНОВИ ПРОИЗВОДИ</h3>
                    <a class="button rounded-pill border border-light py-2 px-3 mt-5 text-light"
                       href="{% url 'recentAccessories' %}"
                       style=" background-color: transparent; text-decoration: none">ВИДИ ПОВЕЌЕ
                    </a>
                </div>
            </div>
            <div class="col d-flex justify-content-center align-items-center">

                <img id="myImage1"
                     src="https://cdn.shopify.com/s/files/1/0357/5673/products/moon-necklace-gold-lifestyle-1.jpg?v=1677152797"
                     style="width: 32rem; height: 23rem" alt="something">
            </div>
        </div>
        <div class="container text-center align-items-center" style="margin-top: 3rem; margin-bottom: 3rem">
            <h4 class="text-bold">РАЧНО ИЗРАБОТЕН ЖЕНСКИ НАКИТ ЗА СЕКОЈА ПРИГОДА</h4>
            <span>2000 година, Охрид</span>
        </div>
        <div class="container" style="background-color: #E5C3A6; height: 4rem">
            <div>

            </div>
            <div class="row">
                <form class="col-4 d-flex mt-3" id="search-form" action="search_products" method='POST'
                      style="height: 2.3rem">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                           id="search-input" name="query">
                    <button class="btn btn-light" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                        </svg>
                    </button>
                </form>
                <form class="col-8 d-flex mt-3" id="filter-form" method="POST" action="{% url 'home' %}"
                      style="padding-left: 3rem;">
                    {% csrf_token %}
                    <div class="d-flex justify-content-between px-4" style="color: #2B0320; ">
                        <div class="px-1">
                            <label for="min-price-input pe-3">Цена:</label>
                            <input type="number" class="rounded text-center text-muted"
                                   style="background-color: #F6E4FF; border: 2px solid #DBBFD1; width: 6rem"
                                   id="min-price-input"
                                   name="min_price" value="0">
                        </div>
                        <div>
                            <label for="max-price-input pe-5">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#2B0320"
                                     class="bi bi-dash" viewBox="0 0 16 16">
                                    <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                                </svg>
                            </label>
                            <input type="number" class="rounded text-center text-muted" id="max-price-input"
                                   style="background-color: #F6E4FF; border: 2px solid #DBBFD1; width: 6rem"
                                   name="max_price"
                                   value="10000">
                        </div>

                    </div>
                    <div class="ps-4" style="width: 17rem; margin-left: 5rem;">
                        <select id="mySelect" class="form-select form-select-sm" aria-label=".form-select-sm example"
                                name="selectCategory">
                            <option selected>Изберете категорија</option>
                            <option value="obetki">Обетки</option>
                            <option value="gjerdani">Ѓердани</option>
                            <option value="alki">Алки</option>
                            <option value="broshovi">Брошови</option>
                            <option value="prsteni">Прстени</option>

                        </select>
                    </div>

                    <div class="ps-5">
                        <button class="btn text-light border border-light p-1" style="background: transparent"
                                type="submit" id="submit-button">Филтрирај
                        </button>
                    </div>
                </form>


            </div>


        </div>
        <div class="container">
            <div class="row mt-4 d-flex justify-content-evenly">
                {% for a in accessories %}

                    <div class="col-3 p-0 mx-2 mt-3">
                        <div class="card">
                            <div class="image-container">
                                <img src="{{ a.mainImage }}" class="card-img-top p-1 px-2" style="height: 19rem">
                                <img src="{{ a.secondImage }}" class="card-img-top p-1 px-2 hover-image"
                                     style="height: 19rem">
                            </div>

                            <div class="card-body text-center">
                                <h6 class="card-title fw-bold"
                                    style="font-family: 'Comic Sans MS'">{{ a.name.upper }}</h6>
                                <p class="card-text">{{ a.price }} ден. </p>
                                {% if a.quantity <= 0 %}
                                    <p class="card-text">Достапна количина: 0 ден. </p>
                                {% else %}
                                    <p class="card-text">Достапна количина: {{ a.quantity }} </p>
                                {% endif %}

                                {% if a.quantity > 0 %}
                                    <button class="button rounded-pill border border-light py-2 px-3 text-light"
                                            style="background-color: #784D59; ">

                                        <form method="post" action="{% url 'details' %}">
                                            {% csrf_token %}

                                            <input type="hidden" value="{{ a.name }}" name="name" id="name">


                                            <input class="border-0" type="submit"
                                                   style="background-color: transparent;color: #F6E4FF "
                                                   value="ВИДИ ПОВЕЌЕ">
                                        </form>
                                    </button>
                                {% endif %}
                            </div>
                        </div>
                    </div>




                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container-fluid d-flex align-items-center justify-content-center"
         style="background-color: #E5C3A6; height: 5rem; margin-top: 125rem ">
            <span class="pe-2"><svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor"
                                    class="bi bi-envelope-at" viewBox="0 0 16 16">
  <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2H2Zm3.708 6.208L1 11.105V5.383l4.708 2.825ZM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2-7-4.2Z"/>
  <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648Zm-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z"/>
</svg></span>
        <span class="pe-5">unique@gmail.com</span>
        <span class="pe-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-telephone"
                 viewBox="0 0 16 16">
  <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
</svg>
        </span>
        <span>+389 75 301 213</span>
        </p>

    </div>
{% endblock content %}

</body>
</html>